<?php

/**
 *
 * This file is responsible to dispatch (call) any events that have been registered for the current page by using attributes.
 * It checks if  there are any  listeners registered for the "after_$page"  events and if so,  it starts output buffering to
 * capture the output for the shutdown function.The shutdown function will then execute the hooks for the current page after
 * all  output  has been generated.  When a method has the attribute to run before the page is rendered, it will be executed
 * immediately and the output will be passed by reference to the method so it can modify the output before it is sent to the
 * browser.
 *
 */

/**
 * Dispatches events for the current page.
 *
 * @return void
 */
function dispatch() {
	$script_name = (string) ($_SERVER['SCRIPT_NAME'] ?? '');
	if ($script_name === '') {
		return;
	}

	$page = basename($script_name, '.php');
	$html_output = '';
	$before_event = "before_render_$page";
	$after_event = "after_render_$page";
	$has_before_listeners = \Frytimo\Fusor\resources\classes\fusor_dispatcher::has_listeners($before_event);
	$has_after_listeners = \Frytimo\Fusor\resources\classes\fusor_dispatcher::has_listeners($after_event);

	// Capture the current output buffer level so we can restore it after the shutdown function has executed. This is important because the shutdown function will execute after all output has been generated and we want to make sure that any output generated by the shutdown function does not get sent to the browser before the output generated by the page itself.
	$fusor_buffer_base_level = ob_get_level();
	$fusor_buffer_target_level = $fusor_buffer_base_level;

	// check if the current page has any listeners registered for "before_$page" and if so, start output buffering to capture the output for the shutdown function
	if ($has_before_listeners) {
		// The html is passed by reference to the event so it can be modified by the listeners before it is sent to the browser.
		$event = new \Frytimo\Fusor\resources\classes\fusor_event($before_event, data: ['html' => &$html_output]);
		\Frytimo\Fusor\resources\classes\fusor_dispatcher::dispatch($event);
	}

	// Only start output buffering if there are listeners registered for the "after_$page" event. This is important because we don't want to start output buffering if there are no listeners registered for the "after_$page" event because it will cause the output to be sent to the browser before the shutdown function has executed.
	if ($has_after_listeners) {
		ob_start();
		$fusor_buffer_target_level += 1;
	}

	// check if the current page has any listeners registered for "after_$page" and if so, register a shutdown function to execute the hooks for the current page after all output has been generated
	if ($has_after_listeners) {
		// register shutdown function to execute hooks for the current page after all output has been generated
		register_shutdown_function(function() use ($after_event, $fusor_buffer_base_level, $fusor_buffer_target_level, &$html_output) {
			$output = '';
			while (ob_get_level() > $fusor_buffer_base_level) {
				if (ob_get_level() === $fusor_buffer_target_level) {
					$output = ltrim((string) ob_get_contents());
					ob_end_clean();
					continue;
				}

				ob_end_flush();
			}

			// Create a new event for the "after_$page" event and dispatch it to all registered listeners. The output is passed by reference to the event so it can be modified by the listeners before it is sent to the browser.
			$event = new \Frytimo\Fusor\resources\classes\fusor_event($after_event, data: ['html' => &$html_output]);

			// Dispatch the event to all registered listeners for the "after_$page" event. The output is passed by reference to the event so it can be modified by the listeners before it is sent to the browser.
			\Frytimo\Fusor\resources\classes\fusor_dispatcher::dispatch($event);

			// Append the output generated by the page to the output generated by the listeners for the "after_$page" event. This is important because we want to make sure that any output generated by the listeners for the "after_$page" event is sent to the browser after the output generated by the page itself.
			echo $output;
		});
	}
}

dispatch();
